server:
  port: 8008
spring:
  redis:
    #数据库索引
    database: 0
    password: 'test'
    timeout: 6000
    cluster:
      nodes:
        - 192.168.80.128:6371
        - 192.168.80.128:6372
        - 192.168.80.128:6373
        - 192.168.80.128:6374
        - 192.168.80.128:6375
        - 192.168.80.128:6376
      max-redirects: 3  # 获取失败 最大重定向次数
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数(使用负值表示没有限制) 默认为8
        max-wait: -1 # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1 单位ms
        max-idle: 8 # 连接池中的最大空闲连接 默认为8
        min-idle: 0 # 连接池中的最小空闲连接 默认为0
