server:
  port: 8008
spring:
  redis:
    database: 0
    timeout: 6000
    # 单机
    host: 192.168.80.128
    port: 6379
    password: zdax_linktool
    # 集群配置
#    cluster:
#      max-redirects: 3
#      nodes:
#        - 192.168.80.128:6379
#        - 192.168.80.128:6379
#        - 192.168.80.128:6379
#        - 192.168.80.128:6379
#        - 192.168.80.128:6379
#        - 192.168.80.128:6379
    # 哨兵
#    sentinel:
#      master: mymaster
#      nodes: 192.168.80.128:6379,192.168.80.128:6379,192.168.80.128:6379
#      password: zdax_linktool
    # 线程池
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数(使用负值表示没有限制) 默认为8
        max-wait: -1 # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1 单位ms
        max-idle: 8 # 连接池中的最大空闲连接 默认为8
        min-idle: 0 # 连接池中的最小空闲连接 默认为0
